services:
  - type: web
    name: auth-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: SUPABASE_URL
        value: https://ofjnkkcxugdtddyevjoi.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
